version: '3'

services:
    proxy:
        image: nginx:1.11.6-alpine
        ports:
            - 81:81
        volumes:
          - ./docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
        restart: always
        depends_on:
            - api

    db:
        image: postgres:10.1-alpine
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=*EasyL0ck*


    api:
        build:
          context: .
          dockerfile: ./docker/api/Dockerfile
        entrypoint:
          - /django-entrypoint.sh
        volumes:
          - .:/code
        ports:
          - 8000:8000
        environment:
          - SECRET_KEY=changemeinprod
          - DB_USER=root
          - DB_PASSWORD=*EasyL0ck*
        depends_on:
          - db
    app:
      build:
          context: .
          dockerfile: ./docker/app/Dockerfile
      entrypoint:
        - /app-entrypoint.sh
      volumes:
        - .:/code
      depends_on:
        - api