# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-17 10:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lock', '0002_auto_20181117_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.CharField(choices=[('OWNER', 'owner'), ('GUEST', 'guest')], default='GUEST', max_length=5)),
                ('expiration', models.DateTimeField(blank=True, null=True)),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lock.Lock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
