# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-17 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lock', '0002_auto_20181117_1029'),
        ('rights', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='right',
            unique_together=set([('right', 'user', 'lock')]),
        ),
    ]
