# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-20 17:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rights', '0002_auto_20181117_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='right',
            name='stop_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
