# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-17 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lock',
            name='members',
        ),
        migrations.RemoveField(
            model_name='lock',
            name='owner',
        ),
    ]
